//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Log4net : global::System.Configuration.ApplicationSettingsBase {
        
        private static Log4net defaultInstance = ((Log4net)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Log4net())));
        
        public static Log4net Default {
            get {
                return defaultInstance;
            }
        }
    }
}
